### ISSUE TITLE
network nulls

### ISSUE THREAD

**Issue by mycotonia** [lessardlab/R-Stats-Questions#2]
Hello

here is the updated code for the maples

I added my question to the code. I hope it's clear, if not let me know.

Qmyc_meta_rare_apr20.xlsx
[MycNET_testJuly9.txt](https://github.com/lessardlab/R-Stats-Questions/files/4915047/MycNET_testJuly9.txt)

[Qmyc_meta_rare_apr20.xlsx](https://github.com/lessardlab/R-Stats-Questions/files/4915051/Qmyc_meta_rare_apr20.xlsx)
[Qmyc_comm_rare1k_apr20.xlsx](https://github.com/lessardlab/R-Stats-Questions/files/4915053/Qmyc_comm_rare1k_apr20.xlsx)

**Comment by fgabriel1891** [comment]
code sent by slack!
