### ISSUE TITLE
global polymorphism project

### ISSUE THREAD

**Issue by jplessard** [lessardlab/R-Stats-Questions#3]

**Comment by fgabriel1891** [comment]
JP, you can add code as with codeblocks (<>) button. 


`library(xxx)`

**Comment by jplessard** [comment]
#### DATA PREPARATION #### 

#datamatching = polymorphism database 
#lat-longGABI = GABI database with lat/long coordinates
### 1. Creating data frame with poly_id ###

specieslist<-read.csv("matched-polymorphism_bg.csv",stringsAsFactors = TRUE)
occ<-read.csv("Lat-Long_Data_GABI.csv",stringsAsFactors = TRUE)

occ$valid_species_name <- factor(occ$valid_species_name, levels = levels(specieslist$taxon_code))
occ$poly_id <- 0

for(i in 1:nrow(occ)){
  temp<-subset(specieslist,specieslist$taxon_code==occ$valid_species_name[i])
  occ$poly_id[i]<-temp$poly_id[1]
}

occ_match<-occ[,-6] #elevation has too many NAs  
occ_match<-na.omit(occ_match)#remove NAs to be able to attribute continent

### 2. Matching Continents Per Occurrence ###

library(rworldmap)
library(rgeos)
library(maptools)
library(cleangeo)  ## For clgeo_Clean()
library(raster)
library(sp)

coords<-as.data.frame(cbind(occ_match$dec_long,occ_match$dec_lat))
colnames(coords)<-c("Lat","Long")
coords<-na.omit(coords)

**Comment by jplessard** [comment]
It goes well to this point

**Comment by jplessard** [comment]
coords<-SpatialPointsDataFrame(coords=coords,data=coords,proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
#convert coordinates into spatial object


cont<-rgdal::readOGR("~/Documents/Work/Concordia/TEACHING/Supervision/MSc/Frédérique Larichelière/Masters Project (Frederique)/FINAL SCRIPT/ne_50m_admin_0_countries")
proj4string(coords)<- proj4string(cont) 

points<-over(coords,cont)#must remove NAs from dataframe

occ_match["Continent"]<-points$CONTINENT

**Comment by jplessard** [comment]
Then I get an error message here when trying to run: coords<-SpatialPointsDataFrame

Warning message:
In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum WGS_1984 in CRS definition,
 but +towgs84= values preserved

**Comment by jplessard** [comment]
For some reason I am still not able to upload data here

**Comment by fgabriel1891** [comment]
Please upload the data and files in the "code" by drag and drop.  I saw that is easier that way. the repo is private. I'll check it asap.

**Comment by fgabriel1891** [comment]
I meant in the code tab of the following repo: https://github.com/lessardlab/GlobalPolyMorp
